# Generated by Django 4.2.7 on 2026-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image_product_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(blank=True, default='', verbose_name='Arabic Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='English Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Arabic Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='English Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription_ar',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Arabic Short Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDescription_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='English Short Description'),
        ),
    ]
