# Generated by Django 4.2.7 on 2026-01-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_section_product_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured Section'),
        ),
    ]
