# Generated by Django 4.2.7 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_adminuser_loginattempt_product_type_adminsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Gold Price per Gram ($)')),
                ('silver_price_per_gram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Silver Price per Gram ($)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metal Price',
                'verbose_name_plural': 'Metal Prices',
                'db_table': 'metal_prices',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight in grams'),
        ),
    ]
