# Generated by Django 4.2.7 on 2026-02-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_metalprice_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Manufacturing Cost per Gram (المصنعية)'),
        ),
    ]
