# Generated by Django 6.0.4 on 2026-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_manufacturing_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Arabic Name')),
                ('name_en', models.CharField(max_length=50, verbose_name='English Name')),
                ('color', models.CharField(default='#667eea', max_length=20, verbose_name='Badge Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
            },
        ),
        migrations.RemoveField(
            model_name='metalprice',
            name='gold_price_per_gram',
        ),
        migrations.RemoveField(
            model_name='metalprice',
            name='silver_price_per_gram',
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_800_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_800_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_925_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_925_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_999_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='fine_999_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_18_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_18_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_21_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_21_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_24_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metalprice',
            name='karat_24_sell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('gold', 'Gold / ذهب'), ('silver', 'Silver / فضة'), ('accessories', 'Accessories / إكسسوارات')], default='silver', max_length=20, verbose_name='Product Type'),
        ),
    ]
