# Generated by Django 6.0.4 on 2026-04-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_badge_remove_metalprice_gold_price_per_gram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='karat',
            field=models.CharField(blank=True, choices=[('24K', '24K (Gold)'), ('21K', '21K (Gold)'), ('18K', '18K (Gold)'), ('999', '999 (Silver)'), ('925', '925 (Silver)'), ('800', '800 (Silver)')], default='21K', max_length=10, null=True, verbose_name='Karat/Fineness'),
        ),
    ]
